### ISSUE TITLE
`sao user/repo#dev` doesn't seem to copy branch content

### ISSUE THREAD

**Issue by nmrshll** [saojs/sao#100]
## What I did
I've got a repo with branches, one of which is called [react-tailwind](https://github.com/nmrshll/frontend-scaffolds/tree/react-tailwind)

I tried to scaffold with its contents by running (as the docs say `sao user/repo#dev`):
```
sao nmrshll/frontend-scaffolds#react-tailwind
```

## What I expected
content from branch `react-tailwind` to get copied to the folder where I ran the command

## What happened instead
content from branch `master` got copied to the local folder

Is this a known bug ? a new bug ? or am I simply using it wrong ?

(ps: thanks for this tool ! seems like it's the only scaffold tool that does what you'd expect intuitively of a scaffold tool)

**Comment by nmrshll** [comment]
I didn't try to clone and fix this project, but here's a temporary workaround for this, with a bash function to clone from a branch:

```sh
      ghcp() {
        if [ ! -e ${2} ]; then echo "${2} set " && BRANCH=${2}; else BRANCH=master; fi
        curl "https://codeload.github.com/${1}/zip/${BRANCH}" | tar -xf - -C .
      }
```

use with
```
ghcp nmrshll/frontend-scaffolds react-tailwind
```

**Comment by egoist** [comment]
Confirmed working correctly with v1

<img width="728" alt="2018-11-10 8 43 40" src="https://user-images.githubusercontent.com/8784712/48301450-5d81af00-e529-11e8-8e2d-51b3cf0c0353.png">

**Comment by nmrshll** [comment]
Works like a charm now ! Thanks a lot for this work !
