### ISSUE TITLE
Conditional prompt

### ISSUE THREAD

**Issue by pablopunk** [saojs/sao#103]
Is it possible to show or not show a prompt based on another prompt answer?. For example:

```js
module.exports = {
  prompts: {
    ava: {
      type: 'list',
      message: 'Do you want to test your code with `ava`?',
      choices: [
        'yes',
        'no'
      ]
    },
    coverage: { // <= I don't want to ask this if answers.ava == 'no'
      type: 'list',
      message: 'Do you want test code coverage?',
      choices: [
        'yes',
        'no'
      ]
    }
  }
}
```

**Comment by takanakahiko** [comment]
@pablopunk You can use `when` in prompts.

prompt syntax is based on https://github.com/SBoudrias/Inquirer.js/ .

example:
```
module.exports = {
  prompts: {
    ava: {
      type: 'list',
      message: 'Do you want to test your code with `ava`?',
      choices: [
        'yes',
        'no'
      ]
    },
    coverage: { // <= I don't want to ask this if answers.ava == 'no'
      when: ({ava}) => ava==='yes',
      type: 'list',
      message: 'Do you want test code coverage?',
      choices: [
        'yes',
        'no'
      ]
    }
  }
}
```

See also: https://github.com/takanakahiko/template-clasp/blob/7786b5e80584d4019421b0d4a722664c7e1b826a/sao.js#L27

**Comment by pablopunk** [comment]
@takanakahiko Awesome, thanks!

**Comment by egoist** [comment]
btw `type: 'confirm'` is better if the `choices` is either `yes` or `no`. 🤔

**Comment by takanakahiko** [comment]
I forgot it! Thank you for the supplement!

**Comment by pablopunk** [comment]
@egoist @takanakahiko

Thanks to both! I actually have a list of choices now (not only “yes” and “no”) so I’ll keep using “list”. But I’ll keep that in mind, thanks
