### ISSUE TITLE
Copy only files inside a specific folder in the templatesDir

### ISSUE THREAD

**Issue by brpaz** [saojs/sao#106]
Hello.
In a generator I am building, I have a couple of directories inside the "template" dir.

Based on an answer from the user , I want to copy only the files from one of the sub folders.
The issue I am having is that SAO, always copy the sub folder itself and not only the files. I have tried many ways from changing the templateDir, files, and filters and nothing seems to work.

Maybe its a just a matter of a wrong glob pattern I am using but I tried many variants.

My last try have this code:

```javascript
actions() {
    return [{
        type: 'add',
        files: `${this.answers.tpl}/**`,
      }
    ]
  }
```

Any ideas or better ways to do this?

**Comment by silvandiepen** [comment]
@brpaz Have you in some way figured this out?

**Comment by brpaz** [comment]
@silvandiepen I don´t remember excatly what this issue was about, but I have this in a generator and it´s working:

```js
 actions() {
    return [
      {
        type: 'add',
        files: '**',
        templateDir: path.join('template', this.answers.actionType),
        filters: {
          Dockerfile: this.answers.actionType === 'docker' || this.answers.docker,
        },
        data: {
          nameSlug: slug(this.answers.name),
        },
      },
    ];
  },
```

Not sure `templateDIr` was already availalbe when I created this issue.
