### ISSUE TITLE
Cannot find tmp dir in circleci

### ISSUE THREAD

**Issue by foryuki** [saojs/sao#115]
Tests in cricle ci always failed with this error:

```bash
Error: ENOENT: no such file or directory, open '/tmp/sao-mock-d6e10b5de0519cd183b7/output/readme.md'
```
[see circle ci failed build here](https://circleci.com/gh/foryuki/sao-node-basis/6)

It looks like [this line of code](https://github.com/saojs/sao/blob/master/lib/mock.js#L20) makes the build fail.
Maybe due to os permission?

**Comment by egoist** [comment]
hmm seems you have `template/README.md` instead of `template/readme.md`.

**Comment by foryuki** [comment]
@egoist 😂 I'm so sorry for my carelessness, and thanks for your reply
