### ISSUE TITLE
How to use Sao v1 from a standalone CLI app?

### ISSUE THREAD

**Issue by lirantal** [saojs/sao#123]
How should Sao be called programmatically from a bin package?

i.e:
```js
const sao = require('sao')
sao({
  outDir: 'somedirectory'
})
```

What else should be provided to run Sao to scaffold a proejct?
I'm specifically interested in the use-case where my module would be invoked such as:
```bash
npx my-sao-generator my-new-project-name
```

Reference: this was asked before at https://github.com/saojs/sao/issues/50 but the link is broken and I can only assume it relates to the previous version of Sao.

**Comment by egoist** [comment]
Check out the code of SAO CLI as an example: https://github.com/saojs/sao/blob/master/bin/cli.js#L10

Another required option besides `outDir` is `generator` which is path to your generator.

I will update the API docs when I have some time.

**Comment by lirantal** [comment]
I did see this but it [looks like](https://github.com/saojs/sao/blob/4fc26cce053d70bf1ca72421c87d68b47a9fbd38/lib/parseGenerator.js#L30) it's requiring the generator to live on npm/github/etc while in reality it just lives inside the actual package itself which has a saofile and it doesn't need to get downloaded again since I'm already invoking it with npx 

Will be happy to update the docs.

**Comment by lirantal** [comment]
Ahh, looks like I can give it a full path to the saofile.js in the project. Gonna try that.

**Comment by egoist** [comment]
yeah btw here's another module that's using SAO under the hood: https://github.com/egoist/poi/blob/master/create-poi-app/bin/cli.js

**Comment by lirantal** [comment]
Indeed. I ended up doing something similar:

```js
#!/usr/bin/env node
'use strict'

const path = require('path')
const sao = require('sao')

const generator = path.resolve(__dirname, '../')
const outDir = path.resolve(process.argv[2] || '.')
sao({generator, outDir})
  .run()
  .catch(err => {
    console.trace(err)
    process.exit(1)
  })
```

Where and which docs should I update to document this?

**Comment by egoist** [comment]
should be this page https://saojs.org/api.html
