### ISSUE TITLE
Allow to set custom template path

### ISSUE THREAD

**Issue by egoist** [saojs/sao#13]
By default if `sao.js` exists the template path would be `./template` otherwise it would be `./`, I want to introduce a `templatePath` option for setting this manually, for example I want to copy `./` but also have `sao.js`

**Comment by kristianmandrup** [comment]
Has this been done or when is it scheduled for? Should be a very small/easy change to make?

**Comment by egoist** [comment]
@kristianmandrup ah yeah, but as `templateFolder` https://sao.js.org/#/create?id=templatefolder
