### ISSUE TITLE
Question regarding packages as sub-generators

### ISSUE THREAD

**Issue by henriquehbr** [saojs/sao#158]
The documentation for v1 has a section about [sub-generators](https://v1.saojs.org/saofile.html#sub-generators), explaining their usage, more specifically, in two different manners, being them, as a path to the generator, or a package:

```js
module.exports = {
  subGenerators: [
    {
      name: 'foo',
      // A path to the generator, relative to the saofile
      generator: './generators/foo'
    },
    {
      name: 'bar',
      // Or use a package, like `sao-bar` here
      // It's also resolved relative to the saofile
      generator: 'sao-bar'
    }
  ]
}
```

From where exactly the package is retrieved? i'm not sure if it's from npm, or from the filesystem, also, does it works with monorepos?

**Comment by egoist** [comment]
it follows the same rule of the cli pattern, `sao ./foo` will fetch the generator from the local folder `./foo`, `sao nm` will instead use `sao-npm` the npm package.

**Comment by egoist** [comment]
but in this case the npm package is resolved from the file system, relative to the saofile instead of downloading from npm.

**Comment by henriquehbr** [comment]
Got it, thank you for the quick response and the great work you're doing with SAO, just discovered the project and it's already my favorite option for project scaffolding :)
