### ISSUE TITLE
Instead of looking for `sao.js` shouldn't we use `package.json`'s "main" property?

### ISSUE THREAD

**Issue by niftylettuce** [saojs/sao#40]
I think we should be using `"main"` in `package.json` instead of having to define a file called `sao.js` or leave it up to the root to get copied.

**Comment by egoist** [comment]
Some packages do have a `main` property but are not SAO templates. maybe introduce an `sao` property to set the name of config file?

**Comment by niftylettuce** [comment]
agreed

**Comment by niftylettuce** [comment]
Perhaps use @egoist https://github.com/davidtheclark/cosmiconfig?

**Comment by egoist** [comment]
how do you use a custom config file in that way?

**Comment by niftylettuce** [comment]
just as you specified, `sao` key in package.json

**Comment by niftylettuce** [comment]
this isn't really needed though
