### ISSUE TITLE
BUG: Cannot override `website` prompt

### ISSUE THREAD

**Issue by niftylettuce** [saojs/sao#43]
It ALWAYS outputs `https://github.com/Your Name/Package Name` regardless of customization of default values!!

**Comment by niftylettuce** [comment]
e.g.

```js
    website: {
      message: 'What is your GitHub repo url',
      default(answers) {
        return `https://github.com/${slug(answers.username)}/${slug(
          answers.name
        )}`;
      },
      store: true
    },
```

Will always put a different default (e.g. the one mentioned in comment above), not sure why?

Only occurs for `website` keyword

**Comment by egoist** [comment]
You are using `store` option so it will only use the default value for the first time.

**Comment by niftylettuce** [comment]
is there a way to clear it from cache?

**Comment by egoist** [comment]
I think `--skip-store` or `--remove-store` will do

**Comment by egoist** [comment]
the cached is stored by `package-name + package-version`, so a new version of your package will not use the cache as well.

**Comment by niftylettuce** [comment]
ty
