### ISSUE TITLE
sao organization

### ISSUE THREAD

**Issue by niftylettuce** [saojs/sao#46]
@egoist I invited you to become an owner of https://github.com/saojs

are you interested in making this into an organization to ensure its existence?

**Comment by egoist** [comment]
Sure.

**Comment by niftylettuce** [comment]
feel free to transfer the repos there, update links/docs as necessary, and add a cool avatar or something!

**Comment by niftylettuce** [comment]
@egoist I added a logo and stuff for now ⚔️ 

<img width="709" alt="screen shot 2017-08-20 at 12 03 03 am" src="https://user-images.githubusercontent.com/523141/29491980-ff68b32c-853a-11e7-8422-a8c4a3669ceb.png">
![crossed-swords](https://user-images.githubusercontent.com/523141/29491981-ff697564-853a-11e7-80f0-7cc6c823c3bb.png)
