### ISSUE TITLE
Possible to add me to NPM?

### ISSUE THREAD

**Issue by niftylettuce** [saojs/sao#47]
I won't publish without your acceptance, but just in case of anything it'd be awesome if I had NPM ownership?

cc @egoist could you `npm owners add niftylettuce`?

**Comment by egoist** [comment]
We should add a contributing guide first, basically I use https://github.com/egoist/changelog.md to update CHANGELOG.md and then run `npm publish`

**Comment by niftylettuce** [comment]
@egoist should we use `np` instead of `npm publish`?

e.g.

```md
# Install the np module
npm i -g np
# Publish a new version of your package!
np patch
```

**Comment by egoist** [comment]
but changelog.md already updates package version and creates git tag for you.

**Comment by niftylettuce** [comment]
dude you are making the damn coolest packages I've seen in such a long time

<https://github.com/egoist/changelog.md> 🆗 ⭐️ ⭐️ ⭐️

**Comment by egoist** [comment]
my equivalent to np is actually https://github.com/egoist/kanpai , np is nice but I don't want it to 

> Reinstalls dependencies to ensure your project works with the latest dependency tree

**Comment by Atinux** [comment]
@egoist @niftylettuce Hi :)

Actually, I always forget to check CHANGELOG.md and I don't think I'm the only one :/

But I always check the Releases tab on Github, I found a nice process and it works pretty nice, it can interest you guys:

```bash
np && release`
```

And that's it!

See https://github.com/sindresorhus/np & https://github.com/zeit/release

**Comment by egoist** [comment]
@Atinux yep, will try for the next release.

**Comment by egoist** [comment]
`release` actually never works for me 😨

<img width="528" alt="2017-10-25 10 46 33" src="https://user-images.githubusercontent.com/8784712/32005295-78f25e58-b9d6-11e7-9d0c-d8f95eacd801.png">

**Comment by egoist** [comment]
FYI now we have semantic-release set up! It automatically publishes new versions and updates GitHub Releases page. So I can close this now 🤗
