### ISSUE TITLE
Ability for `post` hook to be a promise

### ISSUE THREAD

**Issue by niftylettuce** [saojs/sao#49]
Right now I don't believe it's possible to use Promises / async / await in a hook.

e.g. `async hook(ctx, stream) {` never executes

**Comment by niftylettuce** [comment]
Doh, had my syntax wrong 😆 

```js
post: async ctx => {
```

**Comment by egoist** [comment]
Hmm I think `async post() {}` would also work.

**Comment by niftylettuce** [comment]
The prompt hung for me and didn't do anything @egoist - maybe we should catch exceptions and log them?

**Comment by egoist** [comment]
Ah yeah, I'm currently refactoring this.

**Comment by egoist** [comment]
Hmm does the exceptions have anything to do with the `post` hook?
