### ISSUE TITLE
Document how to create a CLI that uses sao

### ISSUE THREAD

**Issue by niftylettuce** [saojs/sao#50]
e.g. `npm install -g foobar` and then `foobar ProjectName` would basically run `sao foobar ProjectName`

@egoist what would documentation for this look like in the readme?  should we suggest `execSync` with `stdio: 'inherit'`?

**Comment by egoist** [comment]
Like this, https://github.com/nuxt-community/create-nuxt-app/blob/master/packages/create-nuxt-app/cli.js The API is not documented though

**Comment by egoist** [comment]
Added https://sao.js.org/#/advanced/standalone-cli
