### ISSUE TITLE
stream.fileContents order always changes (so snapshots are not accurate)

### ISSUE THREAD

**Issue by niftylettuce** [saojs/sao#55]
with the test api the `stream.fileContents` is not always in the same order

e.g. travis tests fail because they're in a different order than locally

https://travis-ci.org/lassjs/lass (see build for v0.0.4)

**Comment by niftylettuce** [comment]
we should use https://github.com/hughsk/path-sort probably

**Comment by egoist** [comment]
I think you mean `stream.fileList`? 

<img width="246" alt="2017-09-02 6 37 34" src="https://user-images.githubusercontent.com/8784712/29994897-edd6b7ac-900d-11e7-99b7-8ff82ceac531.png">

from the diff it seems there's `LICENSE` in new snapshot but not in old snapshot.
