### ISSUE TITLE
Input is being incorrectly escaped

### ISSUE THREAD

**Issue by niftylettuce** [saojs/sao#58]
When rendered with EJS, input prompts entered such as , what is your name? with a value of `Nick's Code` would get escaped to `Nick&#39;s Code`.  i think this is a core sao bug?

**Comment by egoist** [comment]
<img width="537" alt="2017-09-09 2 20 20" src="https://user-images.githubusercontent.com/8784712/30237685-17abb300-956a-11e7-9a0b-2fe3e30cc010.png">

maybe no 🤔

**Comment by egoist** [comment]
Try this then

<img width="537" alt="2017-09-09 2 22 51" src="https://user-images.githubusercontent.com/8784712/30237723-80bc87c0-956a-11e7-8d2f-8fb15698b25a.png">

**Comment by niftylettuce** [comment]
Fixed, thx
