### ISSUE TITLE
Shelljs is vulnerable to command injection

### ISSUE THREAD

**Issue by OmgImAlexis** [saojs/sao#60]
Ref: https://snyk.io/test/github/saojs/sao/
Ref: https://snyk.io/vuln/npm:shelljs:20140723

**Comment by egoist** [comment]
we didn't use `shell.exec()` (which is considered vulnerable) in SAO and the fact is that we didn't even use shelljs at all 😅  that's just an argument in [post hook](https://sao.js.org/#/create?id=post-hook)

**Comment by OmgImAlexis** [comment]
Just thought I'd mention it incase anyone else uses snyk and sees the issue. At least now they can just be referred back to this issue.

Shall we close this?

**Comment by egoist** [comment]
yep, and I think maybe I can remove it cuz I haven't seen anyone use it.

**Comment by egoist** [comment]
Ah, fix: it's actually used to run `git init`

**Comment by OmgImAlexis** [comment]
If you just need to run a child process I'd suggest looking at [execa](https://www.npmjs.com/package/execa).

**Comment by egoist** [comment]
@OmgImAlexis yeah, may switch to that, thx!

**Comment by egoist** [comment]
It's removed in `v0.22.2`
