### ISSUE TITLE
How to pass variables to sao

### ISSUE THREAD

**Issue by pablopunk** [saojs/sao#72]
If I'm using `sao` in a CLI tool like this:

```js
sao({
  template: __dirname,
  targetPath: path.resolve(name)
})
```

How can I send custom data to sao's `context`, i.e to use in post hook:

```js
post(ctx) {
  if (ctx.userWantsNpmInstall) {
    ctx.npmInstall()
  }
}
```

**Comment by egoist** [comment]
Why not use a `prompt`?

**Comment by pablopunk** [comment]
@egoist I could as a workaround, but for options like skipping `git init` or `npm install` I don't wanna be prompted every time cause I rarely say 'no' to that.

But it'd still be useful to send some data you get from CLI, like if you want to set a default for a prompt and you don't have enough with `:gitUser:` and all of that:

```js
profilePic: {
  default(answers, context) {
    if (context.custom.gravatarUrl) {
      return context.custom.gravatarUrl
    }
    return 'default'
  }
}
```

**Comment by egoist** [comment]
Another workaround is to parse cli arguments in your sao config file:

```json
const args = require('minimist')(process.argv.slice(2))
// ...

profilePic: {
  default() {
    if (args.customAvatar) {
      return args.customAvatar
    }
    return 'default'
  }
}
```

**Comment by egoist** [comment]
Maybe we can make config file export a function and inject some context as argument?

while using `sao` cli:

```js
// sao.js
module.exports = options => {
  return {
    // ...
  }
}
```

while using sao api:

```js
require('sao')({
  template: {
    fromPath: __dirname,
    options // inject your own options
  }
})
```

**Comment by pablopunk** [comment]
@egoist That sounds good! I'm gonna see if I can do a workaround for now, with the direct parsing of args. But I'd love that feature you're talking about.

**Comment by egoist** [comment]
It should work now in `v0.22.12`: https://sao.js.org/#/create?id=exporting-a-function

```js
sao({
	template: __dirname,
	configOptions: {/* your options */}
})

// in tests
sao.mockPrompts({
	fromPath: __dirname,
	configOptions: {/* your options */}
})
```

**Comment by pablopunk** [comment]
@egoist Awesome! Thanks 🎉

**Comment by kristianmandrup** [comment]
Not clear exactly how this works. 
Are these `configOptions` merged on top or do they entirely replace what is returned by `sao.js`??

**Comment by egoist** [comment]
@kristianmandrup yeah merged using `Object.assign`:

```js
Object.assign(
    {
      flags
    },
	configOptions
)
```

**Comment by kristianmandrup** [comment]
Ah cool, coz I'd like to supply default answers and skip certain prompts like so many ppl have asked for in these issues...

**Comment by kristianmandrup** [comment]
BTW, working on a very powerful [project template generator](https://github.com/kristianmandrup/project-template) that I intend to use with sao :)

**Comment by kristianmandrup** [comment]
Well, I'd actually like not just to merge on top but to remove most of the prompts for which I already have answers. How would I do that when hard coded to `Object.assign`!?
This standard recipe is still not clear to me :P

**Comment by kristianmandrup** [comment]
If only we could supply a custom `getConfig` or `buildConfig` function ;)

**Comment by kristianmandrup** [comment]
Came up with this solution:

```js
module.exports = saoConfig => {
  const promptsNotAnswered = Object.keys(prompts).reduce((acc, key) => {
    const prompt = prompts[key]
    if (!saoConfig.knownAnswers[key]) {
      acc[key] = prompt
    }
    return acc
  }, {})
  return {
    // NOTE: answers made via prompts
    // can be used to build data answers if needed
    data(answers) {
      return saoConfig.knownAnswers
    },
    prompts: promptsNotAnswered,
    // ...
}
```
