### ISSUE TITLE
How to test with/without current folder

### ISSUE THREAD

**Issue by robertherber** [saojs/sao#79]
How do I specify whether to generate a new folder or not when testing? 

Right now I'm developing a plugin that should have `enforceCurrentFolder: true` but I don't even see how I'm able to test it. All I get is:
`SAOError {
    code: 'REQUIRE_CURRENT_FOLDER',
    message: 'You have to initialize this template in current working directory!',
 }`

For another template I've built it would be great to be able to test both ways as well [template-redux-module](https://github.com/robertherber/template-redux-module).

**Comment by egoist** [comment]
You can set `targetPath` to `process.cwd()` to make it generate in current folder.

**Comment by robertherber** [comment]
I can't get your example working. This is my simple test and I get the same error still:
`
// test.js
import path from 'path';
import test from 'ava';
import sao from 'sao';

const template = {
  fromPath: path.join(__dirname, '..'),
  targetPath: process.cwd(),
};

test('default values', async (t) => {
  const stream = await sao.mockPrompt(template, {

  });

  t.snapshot(stream.fileList, 'Generated files');
});
`

Also tried with `targetPath: '/'` and `targetPath: './'`.

**Comment by robertherber** [comment]
Figured it out and submitted a pull request to make your example work! :) #81

**Comment by egoist** [comment]
Released v0.22.14 for this.

**Comment by robertherber** [comment]
Awesome! 🙏
