### ISSUE TITLE
Add option to just install specific packages (npm/yarn)

### ISSUE THREAD

**Issue by robertherber** [saojs/sao#80]
From what I see it's not currently possible to install specific packages through npm/yarn - correct me if I'm wrong. 

When scaffolding things under an already created project it would be great to be able to install specific packages without directly touching package.json. I see that it's supported in the [underlying package](https://www.npmjs.com/package/yarn-install) - so it's just a matter of exposing the functionality through the API.

**Comment by egoist** [comment]
You can just import and use that package 😄

**Comment by robertherber** [comment]
Yeah, for sure! ;) But when it's already there it would make sense to allow packages as arguments to it! :)
