### ISSUE TITLE
1.0 roadmap

### ISSUE THREAD

**Issue by egoist** [saojs/sao#82]
## API rewrite

```js
const sao = new SAO({
	template: './path/to/template'
})

await sao.generate({
	outDir: path.resolve('my-project') 
})

await sao.generate({
	mock: true,
	outDir: path.resolve('my-project') 
})
```

## Combine templates

`template-foo`:

```js
// template-foo/saofile.js
module.exports = {
	templates: ['bar', 'baz']
}
```

`sao foo` will invoke `template-bar` `template-baz` in order.

`sao foo:bar` will invoke `template-bar` only

**Comment by kristianmandrup** [comment]
Great! Would love to see the option to pass in my own custom template engine as an option so that sao can integrate smoothly with [project-template](https://github.com/kristianmandrup/project-template) or any other similar templating engines ;)

**Comment by kristianmandrup** [comment]
Hmm, maybe that is already possible, just hard to understand from the docs how to do this:

```js
  // get template engine
  if (projectConfig.template === 'handlebars') {
    kopyOptions.template = require('jstransformer-handlebars')
  } else if (typeof projectConfig.template === 'string') {
    kopyOptions.template = utils.requireAt(
      fromPath,
      `jstransformer-${projectConfig.template}`
    )
  } else {
    kopyOptions.template = projectConfig.template
  }
```

**Comment by egoist** [comment]
You mean this? https://sao.js.org/#/create?id=custom-template-engine

**Comment by Atinux** [comment]
Hey @egoist

I was trying to add a multiple choices question (like in vue-cli 3) instead of asking a question every time. Is it possible or do you plan to add it to 1.0?

I tried to look into the source code but could not find anything related.

**Comment by egoist** [comment]
@Atinux hmm, what's _a multiple choices question_ 🤔

**Comment by egoist** [comment]
@Atinux I think that's already supported since we're using inquirer under the hood? https://github.com/SBoudrias/Inquirer.js#checkbox---type-checkbox

**Comment by Atinux** [comment]
It works! Thanks @egoist
