### ISSUE TITLE
BUG: --forceNpm uses yarn instead of npm

### ISSUE THREAD

**Issue by nikolajevp** [saojs/sao#87]
How to reproduce:
run `sao github:egoist/template-template --clone --forceNpm --update`

What is expected:
after initialization it will run `npm install`

What is happening:
 after initialization it runs `yarn install`

Started to happen after https://github.com/saojs/sao/compare/v0.22.14...v0.22.15

**Comment by egoist** [comment]
Fixed in 0.22.16

**Comment by nikolajevp** [comment]
thanks! Great response time!
