### ISSUE TITLE
Cannot include EJS partials 

### ISSUE THREAD

**Issue by raphaelcockx** [saojs/sao#96]
I'm using SAO (successfully so far) to generate my own standalone CLI. I'm reusing a set of templates that already contain some EJS code which makes it pretty easy to convert.

However, one part I can't seem to get working is including EJS partials. I've put some social media tags that I reuse across templates in their own .ejs file and would like to include that from the index.html file SAO is copying over. Wherever I put it and however I pass my path, it's never being found. 

For example:

- Just including it next to the index.html file and calling it with `<%- include facebook.ejs %>`: not found
- Putting it in that same spot and calling it with `<%- include ('facebook.ejs') %>`: not found and showing that the single quotes get escaped as `#39`
- Finally: escaping the single quotes with backslashes makes no difference either

Am I missing something here or is it simply not possible to include partials when rendering a template? Thanks for looking into this!

**Comment by egoist** [comment]
Fixed the not found error https://github.com/saojs/kopy/commit/44681e4fce2115accffd9fbc520d1ab8451a5926 stuff like `<%- include('foo') %>` should work

**Comment by raphaelcockx** [comment]
Wow, thanks so much for the quick fix. I'll give it a try later today, but I'm sure thing will work just fine.
